name: Test Codebase

on: [ push, pull_request ]
permissions:
  contents: read

jobs:
  start:
    name: Start State
    runs-on: ubuntu-latest
    steps:
    - name: Starting 🚀🚀🚀
      id: init
      run: |
        echo "Starting linting of ${{ github.repository }}"

  run_all_tests:
    name: Run all Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    needs: start
    steps:
      - name: Checkout for ${{ runner.os }}
        uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  end:
    name: End State
    runs-on: ubuntu-latest
    needs: run_all_tests
    steps:
    - name: Ending ✅✅✅
      id: init
      run: |
        echo "Ending linting of ${{ github.repository }}"