name: Release New Version
on: [push, pull_request]
jobs:

  start:
    name: Starting 🐼🐼🐼
    runs-on: ubuntu-latest
    steps:
    - name: Starting
      id: init
      run: |
        echo "Starting CI/CD of ${{ github.repository }}"


  deploy_to_development:
    name: CI/CD - Development
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    needs: start
    environment:
      name: Development
      url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Create Release
        run: echo 'All done! '




  deploy_to_staging:
    name: CI/CD - Staging
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: start
    environment:
      name: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
  deploy_to_production:
    name: CI/CD - Production
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: deploy_to_staging
    environment:
      name: Production
      url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install